alignment:
  superglue_params:
    superpoint:
      nms_radius: 4
      keypoint_threshold: 0.005
      max_keypoints: -1 # SG default
    superglue:
      weights: outdoor
      sinkhorn_iterations: 100 # SG / DHR default. tried higher number but minimal differences
      match_threshold: 0.2 # JK # cheng change. higher seems to be a little better
  superpoint_weights_path: /nfs/turbo/umms-tocho/code/chengjia/DeeperHistReg/deeperhistreg/dhr_models/superpoint_v1.pth
  superglue_weights_path: /nfs/turbo/umms-tocho/code/chengjia/DeeperHistReg/deeperhistreg/dhr_models/superglue_outdoor.pth
  transform_type: rigid
  do_ransac: True
  device: cuda

infra:
  svs_root: /nfs/mm-isilon/brainscans/dropbox/Slide_Incoming/svs
  annot_root: /nfs/turbo/umms-tocho/code/chengjia/torchsrh2/ts2/playgrounds/pixel_alignment/sections_annot2/
  out_dir: /nfs/turbo/umms-tocho-snr/exp/chengjia/block_align_crop_rigid_ransac
  num_block_per_job: 10
  blocks_csv: /nfs/turbo/umms-tocho/code/chengjia/torchsrh2/histreg/data/to_reg_250225re3.csv

