# @package _global_

defaults:
  - hydra
  - _self_

infra:
  seed: 1000
  float32_matmul_precision: medium
  comment: ${inference.split}
  output_dir: ${hydra:runtime.output_dir}

data:
  splits:
    trainval:
      dataset:
        _target_: ts3.data.slide_dataset.SlideEmbeddingDataset
        embedding_root: /nfs/turbo/umms-tocho-snr/exp/chengjia/silica_cellinf/b1a0cbe3_k1024
        embedding_path_template: "{patient}-{mosaic}/{patient}-{mosaic}-cell_representations.pt"
        class_order: ["0", "1", "2", "3"]
        slides_csv: /nfs/turbo/umms-tocho/code/chengjia/torchsrh2/ts2/utils/silica_eval/playground/data/ucsf_retrospective_val.csv
        balance_instance_class: false
        transform:
          _target_: ts3.data.transforms.CoordBaseTransforms
          max_size: 6000.0
          center: true
      sampler: null
      dataloader:
        _target_: torch.utils.data.DataLoader
        _partial_: true
        collate_fn:
          _target_: ts3.data.collate.SlideEmbeddingMILCollator
        num_workers: 7
        pin_memory: false
        persistent_workers: true
        batch_size: 8
        shuffle: false
        drop_last: false

meta_arch:
  _target_: ts3.meta_arch.meta_arch.SlideABMILOrdinalModule
  num_classes: 4
  criterion:
    _target_: ts3.losses.coral.CORALLoss
    _partial_: true
  model:
    _target_: ts3.models.ordinal.MILOrdinalModel
    #pe:
    #  _target_: ts3.models.ffpe.LearnableFourierPositionalEncoding
    #  G: 1
    #  M: 2
    #  F_dim: 128
    #  H_dim: 256
    #  D: 384
    #  gamma: 2.0
    mil:
      _target_: ts3.models.abmil.GatedABMILRegThenAgg
      input_dim: 384
      hidden_dim: 256
      final_dim: 128
      dropout: 0.5
      regressor_hidden_dims: [128]
      regressor_drop: 0.0
      regressor_bias: true
    head:
      _target_: ts3.models.ordinal.SharedCORALHead
      num_classes: ${meta_arch.num_classes}

inference:
  split: trainval
  checkpoint_path: TODO

trainer:
  _target_: pytorch_lightning.Trainer
  accelerator: auto
  devices: 1
  logger: false
  enable_checkpointing: false
  enable_progress_bar: true
  precision: 32-true

hydra:
  run:
    dir: ${ts3_eval_dir:${inference.checkpoint_path},${infra.comment}}
