# @package _global_

defaults:
  - hydra

infra:
  seed: 1000
  log_dir: /nfs/turbo/umms-tocho-snr/exp/chengjia
  exp_name: TODO
  comment: rtamil_pos_drop2575
  tune_comment: TODO
  float32_matmul_precision: medium

data:
  dataset_common: &dataset_common
    _target_: ts3.data.slide_dataset.SlideEmbeddingDataset
    embedding_root: /scratch/tocho_root/tocho0/chengjia/silica_ucsf_fixpatch/b1a0cbe3_k1024
    embedding_path_template: "{patient}-{mosaic}/{patient}-{mosaic}-cell_representations.pt"
    class_order: ["0", "1", "2", "3"]
    target_transform:
      _target_: ts3.data.base_dataset.LabelIndexTensorTransform
      class_order: ${data.dataset_common.class_order}
  dataloader_common: &dataloader_common
    _target_: torch.utils.data.DataLoader
    _partial_: true
    collate_fn:
      _target_: ts3.data.collate.SlideEmbeddingMILCollator
    num_workers: 7
    pin_memory: false
    persistent_workers: true
  infinite_train_sampler: &infinite_train_sampler
    _target_: ts3.data.samplers.ShardedInfiniteEpochSampler
    _partial_: true
    shuffle: true
  splits:
    train:
      steps_per_epoch: 1250
      dataset:
        <<: *dataset_common
        slides_csv: /nfs/turbo/umms-tocho/code/chengjia/torchsrh2/ts2/utils/silica_eval/playground/data/ucsf_retrospective_train.csv
        balance_instance_class: true
        transform:
          _target_: torchvision.transforms.Compose
          transforms:
            - _target_: ts3.data.transforms.CellDropAugment
              drop_rate: [0.25, 0.75]
              min_cells: 1
              p: 0.5
            - _target_: ts3.data.transforms.StrongCoordAugment
              max_size: 6000.0
            - _target_: ts3.data.transforms.CoordBaseTransforms
              max_size: 6000.0
              center: true
      sampler: *infinite_train_sampler
      dataloader:
        <<: *dataloader_common
        batch_size: 8
        drop_last: true
    trainval:
      dataset:
        <<: *dataset_common
        slides_csv: /nfs/turbo/umms-tocho/code/chengjia/torchsrh2/ts2/utils/silica_eval/playground/data/ucsf_retrospective_val.csv
        balance_instance_class: false
        transform:
          _target_: ts3.data.transforms.CoordBaseTransforms
          max_size: 6000.0
          center: true
      sampler: null
      dataloader:
        <<: *dataloader_common
        batch_size: 8
        shuffle: false
        drop_last: false

meta_arch:
  _target_: ts3.meta_arch.meta_arch.SlideABMILOrdinalModule
  num_classes: 4
  criterion:
    _target_: ts3.losses.coral.CORALLoss
    _partial_: true
  model:
    _target_: ts3.models.ordinal.MILOrdinalModel
    pe:
      _target_: ts3.models.ffpe.LearnableFourierPositionalEncoding
      G: 1
      M: 2
      F_dim: 128
      H_dim: 256
      D: 384
      gamma: 2.0
    mil:
      _target_: ts3.models.abmil.GatedABMILRegThenAgg
      instance_encoder:
        _target_: torch.nn.Sequential
        _args_:
          - _target_: torch.nn.Linear
            in_features: 384
            out_features: 256
          - _target_: torch.nn.ReLU
          - _target_: torch.nn.Dropout
            p: 0.5
      attention_v:
        _target_: torch.nn.Sequential
        _args_:
          - _target_: torch.nn.Linear
            in_features: 256
            out_features: 128
          - _target_: torch.nn.Tanh
      attention_u:
        _target_: torch.nn.Sequential
        _args_:
          - _target_: torch.nn.Linear
            in_features: 256
            out_features: 128
          - _target_: torch.nn.Sigmoid
      attention_w:
        _target_: torch.nn.Linear
        in_features: 128
        out_features: 1
      regressor:
        _target_: ts3.models.abmil.MLPRegressor
        input_dim: 256
        hidden_dims: []
        drop: 0.0
        bias: true
    head:
      _target_: ts3.models.ordinal.SharedCORALHead
      num_classes: ${meta_arch.num_classes}

  optimizer:
    _target_: torch.optim.AdamW
    _partial_: true
    lr: 1.0e-4
    betas: [0.9, 0.999]
    eps: 1.0e-8
    weight_decay: 1.0e-4
    amsgrad: false
  scheduler:
    _target_: torchsrh.optim.cosine_schedule_warmup.get_cosine_schedule_with_warmup
    _partial_: true
    num_warmup_steps: ${int_div:${.num_training_steps},10}
    num_training_steps: ${int_mul:${trainer.max_epochs},${data.splits.train.steps_per_epoch}}
    num_cycles: 0.5

trainer:
  _target_: pytorch_lightning.Trainer
  default_root_dir: ${hydra:runtime.output_dir}

  accelerator: gpu
  devices: 1

  # devices: -1     # DDP ONLY
  # strategy: ddp   # DDP ONLY
  use_distributed_sampler: false # we keep false here even for DDP

  callbacks:
    - _target_: pytorch_lightning.callbacks.ModelCheckpoint
      dirpath: ${hydra:runtime.output_dir}/models
      filename: "epoch{epoch:02d}"
      auto_insert_metric_name: false
      monitor: val/loss
      mode: min
      save_last: true
      save_top_k: -1
      every_n_epochs: 1
    - _target_: pytorch_lightning.callbacks.LearningRateMonitor
      logging_interval: step
  logger:
    - _target_: pytorch_lightning.loggers.TensorBoardLogger
      save_dir: ${hydra:runtime.output_dir}
      name: tb
      version: ""
    - _target_: pytorch_lightning.loggers.CSVLogger
      save_dir: ${hydra:runtime.output_dir}
      name: csv
      version: ""
  max_epochs: 10
  log_every_n_steps: 10
  enable_progress_bar: true
  precision: 16-mixed
  gradient_clip_val: 1.0
  accumulate_grad_batches: 1
