alignment:
  bf_only: True

infra:
  svs_root: /nfs/mm-isilon/brainscans/dropbox/Slide_Incoming/svs
  annot_root: /nfs/turbo/umms-tocho/code/chengjia/torchsrh2/ts2/playgrounds/pixel_alignment/sections_annot2/
  out_dir: /nfs/turbo/umms-tocho-snr/exp/chengjia/block_align_crop_rigid_bf
  num_block_per_job: 1
  blocks_csv: /nfs/turbo/umms-tocho/code/chengjia/torchsrh2/histreg/data/to_reg_bf.csv

