alignment:
  superglue_params:
    superpoint:
      nms_radius: 4
      keypoint_threshold: 0.005
      max_keypoints: -1 # SG default
    superglue:
      weights: outdoor
      sinkhorn_iterations: 100 # SG / DHR default. tried higher number but minimal differences
      match_threshold: 0.2 # JK # cheng change. higher seems to be a little better
  superpoint_weights_path: /nfs/turbo/umms-tocho/code/chengjia/DeeperHistReg/deeperhistreg/dhr_models/superpoint_v1.pth
  superglue_weights_path: /nfs/turbo/umms-tocho/code/chengjia/DeeperHistReg/deeperhistreg/dhr_models/superglue_outdoor.pth
  transform_type: affine 
  do_ransac: True
  device: cuda

infra:
  svs_root: /nfs/mm-isilon/brainscans/dropbox/neuroslides/svs/
  annot_root: /nfs/turbo/umms-tocho/code/chengjia/torchsrh2/ns/utils/sections_annot/sections_annot2/
  out_dir: /nfs/turbo/umms-tocho-snr/exp/chengjia/neuroslides/histreg/block_align_crop_affine_ransac/
  blocks_csv: /nfs/turbo/umms-tocho/code/chengjia/torchsrh2/ns/utils/histreg/config/data/to_reg_2605b.csv
  num_block_per_job: 32

