infra:
  exp_name: ts2/tcga_usup/ijepa
  log_dir: /nfs/turbo/umms-tocho/exp/renly
  comment: dev
  log_gpu: True
  seed: 1000
data:
  set: he
  parser:
    which: CachedCSVParser
    params:
      cached_parser_file:
        train: /nfs/mm-isilon/brainscans/dropbox/data/tsmeta/he_neuro/92b8ad49_slide_all/
        trainval: /nfs/mm-isilon/brainscans/dropbox/data/tsmeta/he_neuro/92b8ad49_slide_toy/
        test_databank: /nfs/mm-isilon/brainscans/dropbox/data/tsmeta/tcga_glioma/69ecabd1_patch40_train/
        test: /nfs/mm-isilon/brainscans/dropbox/data/tsmeta/tcga_glioma/69ecabd1_patch40_trainval/
  transform:
    train:
      which: HistologyTransform
      params:
        base_aug_params: {}
          #laser_noise_config: null
          #base_aug: three_channels
        strong_aug_params:
          aug_list:
          - which: random_resized_crop
            params:
              size: 224
              scale: [0.3, 1.0]
          - which: resize_always_apply
            params:
              size: 224
          - which: color_jitter
            params:
              brightness: 0.4
              contrast: 0.4
              saturation: 0.4
              hue: 0.2
          - which: gaussian_blur
            params:
              kernel_size: 21
              sigma: 1
          aug_prob: 0.5
    trainval: ${.train}
    test:
      which: HistologyTransform
      params:
        base_aug_params: {}
        strong_aug_params:
          aug_list:
          - which: resize_always_apply
            params:
              size: 224
          aug_prob: 1
  dataset:
      which: SingleLevelHierarchicalDataset
      which_process_read: memmap
      params:
        common:
          data_root: /nfs/mm-isilon/brainscans/dropbox/data/root_histology_db/he.plip
          num_transforms: 1
          num_samples: 1
          balance_instance_class: False
        train:
          num_instance_self_replicate: 30
        trainval: {}
  test_dataset:
      which: PatchDataset
      which_process_read: memmap
      params:
          data_root: /nfs/mm-isilon/brainscans/dropbox/data/root_histology_db/he.plip
          num_transforms: 1
          balance_instance_class: False
      negative_class_index: 1
      classes_reorder: [2,0,1]
      camera_ready_classes: [Astro, GBM, Oligo]
  loader:
    params:
      common:
        pin_memory: False
        persistent_workers: True
        prefetch_factor: 4
        num_workers: auto 
      train:
        batch_size: 512
        drop_last: true
        shuffle: true
        collate_fn: 
          which: MBMaskCollator
          params: 
            input_size: 224
            patch_size: 16
            pred_mask_scale: [0.15, 0.2]
            enc_mask_scale: [0.85, 1.0]
            aspect_ratio: [0.75, 1.5]
            nenc: 1
            npred: 4
            allow_overlap: false
            min_keep: 10
      trainval:
        batch_size: 512
        drop_last: False
        shuffle: False
        collate_fn: 
          which: MBMaskCollator
          params: 
            input_size: 224
            patch_size: 16
            pred_mask_scale: [0.15, 0.2]
            enc_mask_scale: [0.85, 1.0]
            aspect_ratio: [0.75, 1.5]
            nenc: 1
            npred: 4
            allow_overlap: false
            min_keep: 10
      test:
        batch_size: 256 
        drop_last: False
        shuffle: False
    trainval_sampler:
      num_samples: 8
      replacement: False
lightning_module:
  which: IJEPASystem
  params:
    model_hyperparams:
      backbone_cf:
        which: vit_small
        params:
          img_size: 224
          patch_size: 16
          # global_pool: ""
          # class_token: False
      pred_params:
        predictor_embed_dim: 192
        depth: 6
    loss_params: {}
    ema_beta: 0.996
    opt_cf:
      which: adamw
      scale_lr: True
      params:
        lr: 0.001
        betas: [0.9, 0.999]
        eps: 1.0e-8
        weight_decay: 0.01
        amsgrad: False
    #opt_cf:
    #  which: lars
    #  scale_lr: True
    #  params:
    #    lr: 0.001
    #    weight_decay: 1.0e-4
    #    momentum: 0.9
    #    #eta: 0.001
    schd_cf:
      which: cos_linear_warmup
      params:
        num_warmup_steps: 0.1
        num_cycles: 0.5
training:
  resume_checkpoint: null
  trainer_params:
    max_epochs: 50
    gradient_clip_val: 0.5
    enable_progress_bar: True
    precision: 'bf16-mixed'
    deterministic: false
  fl32_preci: medium
  trainval:
    freq:
      interval: 10
      unit: "epoch"
testing:
  eval_mode: patch_knn
  save_train_pred: true
  knn:
    do_knn: True
    knn_params:
      batch_size: 1536
      k: 20
      t: 0.07
  tsne:
    interactive: False
    num_patches: [8192]
    which_set: [val]
    embed_images: true
    class_params:
      perplexity: 50
      learning_rate: auto
      init : pca
tune:
  diagonal_items: true
  params:
    lightning_module/params/opt_cf/params/lr:
    - 0.0001
    - 0.0005
    infra/comment:
    - ijepa_1000_lr0.0001
    - ijepa_1000_lr0.0005
