infra:
  dzi_root: ./dzi
  num_mosaic_per_task: null

data:
  data_root: /nfs/turbo/umms-tocho/root_srh_db/UM
  mosaic_runs:
  - NIO_UM_1011/1
  - NIO_UM_1011/2
  - NIO_UM_1011/3
  - NIO_UM_1011/4
  - NIO_UM_1011/5
  - NIO_UM_1016/1
  - NIO_UM_1028/2
  - NIO_UM_1047/1
  - NIO_UM_1047/2
  - NIO_UM_1047/3
  - NIO_UM_1101/2
  - NIO_UM_1113/1
  - NIO_UM_1113b/1
  - NIO_UM_1113b/2
  - NIO_UM_1114/1
  - NIO_UM_1114/2
  - NIO_UM_1114/3
  - NIO_UM_1118/3
  - NIO_UM_1123/3
  - NIO_UM_1125/1
  - NIO_UM_1125/2
  - NIO_UM_1126/1
  - NIO_UM_1126/3
  - NIO_UM_1132/1
  - NIO_UM_1132/3
  - NIO_UM_1141/1
  - NIO_UM_1147/2
  - NIO_UM_1160/2
  - NIO_UM_1165/5
  - NIO_UM_1165/6
  - NIO_UM_1166/1
  - NIO_UM_1166/2
  - NIO_UM_1166/3
  - NIO_UM_1173/3
  - NIO_UM_1177/2
  - NIO_UM_1193/2
  - NIO_UM_1193/3
  - NIO_UM_1209/5
  - NIO_UM_724/2
  - NIO_UM_724/6
  - NIO_UM_724/7
  - NIO_UM_724/8
  - NIO_UM_916/1
  - NIO_UM_929/1
  - NIO_UM_929/2
  - NIO_UM_929/3
  - NIO_UM_937/2
  - NIO_UM_937/3
  - NIO_UM_937b/1
  - NIO_UM_937b/4
  - NIO_UM_938/2
  - NIO_UM_940/2
  - NIO_UM_941/1
  - NIO_UM_944/1
  - NIO_UM_944/4
  - NIO_UM_948/1
  - NIO_UM_950/1
  - NIO_UM_950/2
  - NIO_UM_950/3
  - NIO_UM_969/2
  - NIO_UM_995/1
  - NIO_UM_995/2
  - NIO_UM_998/1

  #data_root: /nfs/turbo/umms-tocho/data/db_nio_mouse/mouse # /nfs/turbo/umms-tocho/root_srh_db/UM #
  #mosaic_runs:
  ##- NIO_UM_937b/4
  ##- NIO_UM_950/3
  #- nio_mouse_1/1
  #- nio_mouse_1/10
  #- nio_mouse_1/11
  #- nio_mouse_1/12
  #- nio_mouse_1/13
  #- nio_mouse_1/14
  #- nio_mouse_1/2
  #- nio_mouse_1/3
  #- nio_mouse_1/4
  #- nio_mouse_1/5
  #- nio_mouse_1/6
  #- nio_mouse_1/7
  #- nio_mouse_1/8
  #- nio_mouse_1/9
  #- nio_mouse_2/1
  #- nio_mouse_2/2
  #- nio_mouse_2/3
  #- nio_mouse_2/4
  #- nio_mouse_3/1
  #- nio_mouse_3/2
  #- nio_mouse_3/3
  #- nio_mouse_3/4
  #- nio_mouse_3/5
  #- nio_mouse_3/6
  #- nio_mouse_3/7
  #- nio_mouse_4/1
  #- nio_mouse_4/2
  #- nio_mouse_4/3
  #- nio_mouse_4/4
  #- nio_mouse_4/5
  #- nio_mouse_4/6
  #- nio_mouse_4/7
  #- nio_mouse_4b/1
  #- nio_mouse_5/1
  #- nio_mouse_5/2
  #- nio_mouse_5/3
  #- nio_mouse_5/4
  #- nio_mouse_5/5
  #- nio_mouse_5/6
  #- nio_mouse_6/1
  #- nio_mouse_6/10
  #- nio_mouse_6/11
  #- nio_mouse_6/2
  #- nio_mouse_6/3
  #- nio_mouse_6/4
  #- nio_mouse_6/5
  #- nio_mouse_6/6
  #- nio_mouse_6/7
  #- nio_mouse_6/8
  #- nio_mouse_6/9
  #- nio_mouse_6b/1
  #- nio_mouse_7/1
  #- nio_mouse_7/10
  #- nio_mouse_7/2
  #- nio_mouse_7/3
  #- nio_mouse_7/4
  #- nio_mouse_7/5
  #- nio_mouse_7/6
  #- nio_mouse_7/7
  #- nio_mouse_7/8
  #- nio_mouse_7/9
  #- nio_mouse_7b/1
  #- nio_mouse_7b/2
  #- nio_mouse_8/1
  #- nio_mouse_8/10
  #- nio_mouse_8/2
  #- nio_mouse_8/3
  #- nio_mouse_8/4
  #- nio_mouse_8/5
  #- nio_mouse_8/6
  #- nio_mouse_8/7
  #- nio_mouse_8/8
  #- nio_mouse_8/9
#