infra:
  exp_name: TODO #ts2/committeedistil/debug_projnorm_vitl_long_noum # ts2/committeedistil/debug_projnorm_vits_long_crd_expv2 #ts2/committeedistil/debug_projnorm_vitb_long_crd_fixbug #ts2/committeedistil/debug_projnorm_vitl_long  #ts2/committeedistil/debug_projnorm_vitb_long
  log_dir: /nfs/turbo/umms-tocho-snr/exp/chengjia
  comment: standaloneeval_37
  log_gpu: True
  seed: 1000
  float32_matmul_precision: medium
data:
  set: he
  parser:
    which: CachedCSVParser
    params:
      cached_parser_file:
        test_databank: /nfs/turbo/umms-tocho/code/chengjia/torchsrh2/ts2/data/tsmeta/tcga_glioma/3438b0a3_patch40_train
        test: /nfs/turbo/umms-tocho/code/chengjia/torchsrh2/ts2/data/tsmeta/tcga_glioma/3438b0a3_patch40_trainval
  #transform:
  #  test:
  #    which: HistologyTransform
  #    params:
  #      base_aug_params: {}
  #      strong_aug_params:
  #        aug_list:
  #        - which: resize_always_apply
  #          params:
  #            size: 224
  #        aug_prob: 1
  transform:
    test:
      which: HistologyTransform
      params:
        base_aug_params:
          do_normalize: False
        strong_aug_params:
          aug_list:
          - which: dinov2_normalize_always_apply
            params: {}
          - which: resize_always_apply
            params:
              size: 224
          aug_prob: 1
  test_dataset:
      which: PatchDataset
      which_process_read: memmap
      params:
          data_root: /nfs/mm-isilon/brainscans/dropbox/data/root_histology_db/he.plip
          num_transforms: 1
          balance_instance_class: False
      negative_class_index: 1
      classes_reorder: [2,0,1]
      camera_ready_classes: [Astro, GBM, Oligo]
  loader:
    params:
      common:
        pin_memory: False
        persistent_workers: False
        prefetch_factor: 8
        num_workers: 7
      test:
        batch_size: 256
        drop_last: False
        shuffle: False
lightning_module:
  which: Dinov2EvalSystem
  params:
    model_hyperparams:
        arch: vit_large
        img_size: 224
        patch_size: 16
        global_pool: "token"
        class_token: True
        block_chunks: 4
        ffn_bias: true
        ffn_layer: "mlp"
        num_register_tokens: 0
        interpolate_antialias: false
        interpolate_offset: 0.1
        layerscale: 1.0e-05
        pretrained_weights: ""
        proj_bias: true
        qkv_bias: true
    pretrained_weights: TODO
#lightning_module:
#  which: Dinov2EvalSystem
#  params:
#    model_hyperparams:
#        arch: vit_large
#        #img_size: 224
#        patch_size: 14
#        global_pool: "token"
#        class_token: True
#        block_chunks: 4
#        ffn_bias: true
#        ffn_layer: "swiglufused"
#        num_register_tokens: 0
#        interpolate_antialias: false
#        interpolate_offset: 0.1
#        layerscale: 1.0e-05
#        pretrained_weights: ""
#        proj_bias: true
#        qkv_bias: true
#    pretrained_weights: TODO
#lightning_module:
#  which: CommitteeDistillationNetwork
#  params:
#    strict: False
#    model_hyperparams:
#      backbone_cf:
#        which: vit_large #resnet34
#        params:
#          img_size: 224
#          patch_size: 16
#          global_pool: "token"
#          class_token: True
#          init_values: 1.0e-6
#      pred_params: null
#      student_proj_params: null
#lightning_module:
#  which: SimCLRSystem
#  params:
#    model_hyperparams:
#      backbone_cf:
#        which: vit_small
#        params:
#          img_size: 224
#          patch_size: 16
#          global_pool: "token"
#          class_token: True
#      proj_params:
#        hidden_layers: [384]
#        n_out: 384
#        activation: relu
#        drop: 0
#        bias: True

testing:
  eval_mode: patch_knn
  save_train_pred: true
  #eval_predictions
  knn:
    do_knn: True
    knn_params:
      batch_size: 1536
      k: 20
      t: 0.07
  tsne:
    interactive: False
    num_patches: [8192]
    which_set: [val]
    embed_images: true
    class_params:
      perplexity: 50
      learning_rate: auto
      init : pca
#tune:
#  diagonal_items: true
#  params:
#    testing/ckpt_path:
#    - 26bc53b7_Aug04-16-16-14_sd1000_lr0.001_uni_tune2/models/ckpt-epoch39-step57240-loss0.00.ckpt
#    - 3d8dbd86_Aug04-16-16-14_sd1000_lr0.001_mahmoodspecial_tune1/models/ckpt-epoch39-step57240-loss0.00.ckpt
#    - 7921bbb2_Aug04-16-16-14_sd1000_lr0.0001_uni_tune6/models/ckpt-epoch39-step57240-loss0.00.ckpt
#    - 817a7220_Aug04-16-16-19_sd1000_lr0.001_all5_tune0/models/ckpt-epoch39-step57240-loss0.00.ckpt
#    - 8f22d45a_Aug04-16-16-14_sd1000_lr0.0001_goodvm_tune7/models/ckpt-epoch39-step57240-loss0.00.ckpt
#    - abc1e6ef_Aug04-16-16-19_sd1000_lr0.001_goodvm_tune3/models/ckpt-epoch39-step57240-loss0.00.ckpt
#    - e7055dce_Aug04-16-16-14_sd1000_lr0.0001_all5_tune4/models/ckpt-epoch39-step57240-loss0.00.ckpt
#    - ecab89cd_Aug04-16-16-14_sd1000_lr0.0001_mahmoodspecial_tune5/models/ckpt-epoch39-step57240-loss0.00.ckpt

tune:
  diagonal_items: true
  params:
    lightning_module/params/pretrained_weights:
    - /nfs/turbo/umms-tocho-snr/exp/chengjia/ts2/he_neuro_dinov2_uniinit/997de344_Aug20-01-14-10_sd1000_dev_tune1/models/eval/training_312499/teacher_checkpoint.pth
    - /nfs/turbo/umms-tocho-snr/exp/chengjia/ts2/he_neuro_dinov2_uniinit/997de344_Aug20-01-14-10_sd1000_dev_tune1/models/eval/training_324999/teacher_checkpoint.pth

#tune:
#  diagonal_items: true
#  params:
#    infra/comment:
#    - uni
#    - conch
#    - virchow
#    - gigapath
#    - plip
#    lightning_module:
#    - which: UNIEvalSystem
#      params:
#        ckpt_path: /nfs/mm-isilon/brainscans/dropbox/exp/models/uni/vit_large_patch16_224.dinov2.uni_mass100k/pytorch_model.bin
#    - which: ConchEvalSystem
#      params:
#        ckpt_path: /nfs/mm-isilon/brainscans/dropbox/exp/models/conch/pytorch_model.bin
#    - which: VirchowEvalSystem
#      params:
#        ckpt_path: /nfs/mm-isilon/brainscans/dropbox/exp/models/virchow/pytorch_model.bin
#    - which: GigapathEvalSystem
#      params:
#        ckpt_path: /nfs/mm-isilon/brainscans/dropbox/exp/models/gigapath/pytorch_model.bin
#    - which: PLIPEvalSystem
#      params:
#        ckpt_path: /nfs/mm-isilon/brainscans/dropbox/exp/models/plip/
