infra:
  exp_name: ts2/scsrh_ibot
  log_dir: /nfs/turbo/umms-tocho-snr/exp/chengjia
  comment: smpt_SE9
  log_gpu: True
  seed: 1000
  float32_matmul_precision: medium

data:
  set: scsrh
  parser:
    which: CachedCSVParser
    params:
      cached_parser_file:
        test_databank: ../data/tsmeta/srh7v1_sc/c191d6d5_cell40_train
        test: ../data/tsmeta/srh7v1_sc/c191d6d5_cell40_trainval
  transform:
    test:
      which: HistologyTransform
      params:
        base_aug_params:
          laser_noise_config: null
          get_third_channel_params:
            mode: three_channels
            subtracted_base: 0.07629394531
          mask_params:
            how_to_process: small_patch #rm_background #
            bg_fill: [9957.5889, 10057.9795]
          #to_uint8: True
        strong_aug_params:
          aug_list:
          - which: center_crop_always_apply
            params:
              size: 48
          aug_prob: 1
  test_dataset:
    which: CellDataset # SingleLevelHierarchicalDataset
    which_process_read: cell_memmap
    params:
      data_root: /nfs/turbo/umms-tocho-snr/exp/chengjia/scsrh_repl_root2/
      num_transforms: 1
      balance_instance_class: False
    classes_reorder: [0, 1, 2, 3, 5, 6, 4]
    camera_ready_classes: [HGG, LGG, Mening, Mets, Normal, Pit, Schwan]
  loader:
    params:
      common:
        pin_memory: False
        persistent_workers: False
        prefetch_factor: 8
        num_workers: 7
      test:
        batch_size: 256
        drop_last: False
        shuffle: False
#lightning_module:
#  which: Dinov2EvalSystem
#  params:
#    model_hyperparams:
#        arch: vit_base
#        img_size: 48
#        patch_size: 4
#        #global_pool: "token"
#        #class_token: True
#        block_chunks: 4
#        ffn_bias: true
#        ffn_layer: swiglufused
#        num_register_tokens: 0
#        interpolate_antialias: false
#        interpolate_offset: 0.1
#        layerscale: 1.0e-05
#        proj_bias: true
#        qkv_bias: true
#    pretrained_weights: TODO
#lightning_module:
#  which: SupConSystem
#  params:
#    model_hyperparams:
#      backbone_cf:
#        which: vit_base
#        params:
#          img_size: 48
#          patch_size: 4
#          global_pool: "token"
#          class_token: True
#          init_values: 1.0e-6
#      proj_params:
#        hidden_layers: [768, 768]
#        n_out: 768
#        activation: relu
#        drop: 0
#        bias: True
#lightning_module:
#  which: SupConSystem
#  params:
#    model_hyperparams:
#      backbone_cf:
#        which: vit_small
#        params:
#          img_size: 48
#          patch_size: 4
#          global_pool: "token"
#          class_token: True
#          init_values: 0
#      proj_params:
#        hidden_layers: [384,384]
#        n_out: 384
#        activation: relu
#        drop: 0
#        bias: True
lightning_module:
  which: MCMSystem
  params:
    model_hyperparams:
      backbone_cf:
        which: vit_small
        params:
          img_size: 48
          patch_size: 4
          global_pool: "token"
          class_token: True
      proj_params:
        hidden_layers: [384]
        n_out: 384
        activation: relu
        drop: 0
        bias: True
    strict: False
#lightning_module:
#  which: FlattenSystem
#  params: {}
testing:
  eval_mode: knn
  save_train_pred: True
  #eval_predictions: 4cf5a93d_Oct14-23-29-19_sd1000_standaloneeval_37
  knn:
    do_knn: True
    knn_params:
      batch_size: 1536
      k: 20
      t: 0.07
  tsne:
    interactive: True
    num_patches: [4096]
    which_set: [val]
    embed_images: true
    class_params:
      perplexity: 50
      learning_rate: auto
      init : pca
  nn_viz:
    query_set: val
    n_sample: 32
    target_set: val
    exclude_same_patient: True
    k: 40
tune:
  diagonal_items: true
  params:
    testing/ckpt_path:
    - ad3cd942_Mar10-17-23-43_sd1000_ibot_1000_lr0.0005_tune1/models/ckpt-epoch53-step360450-loss0.00.ckpt
    - b050cd38_Mar10-17-23-42_sd1000_ibot_1000_lr0.001_tune0/models/ckpt-epoch53-step360450-loss0.00.ckpt
    - c647ab60_Mar10-08-48-03_sd1000_ibot_1000_lr0.001_tune0/models/ckpt-epoch161-step360450-loss0.00.ckpt
    - e1eb758d_Mar10-08-48-03_sd1000_ibot_1000_lr0.0005_tune1/models/ckpt-epoch161-step360450-loss0.00.ckpt
    - ad3cd942_Mar10-17-23-43_sd1000_ibot_1000_lr0.0005_tune1/models/ckpt-epoch53-step360450-loss0.00.ckpt
    - b050cd38_Mar10-17-23-42_sd1000_ibot_1000_lr0.001_tune0/models/ckpt-epoch53-step360450-loss0.00.ckpt
    - c647ab60_Mar10-08-48-03_sd1000_ibot_1000_lr0.001_tune0/models/ckpt-epoch161-step360450-loss0.00.ckpt
    - e1eb758d_Mar10-08-48-03_sd1000_ibot_1000_lr0.0005_tune1/models/ckpt-epoch161-step360450-loss0.00.ckpt
    infra/comment:
    - smpt_SEs36k
    - smpt_SEs36k
    - smpt_SEs36k
    - smpt_SEs36k
    - rmbg_SEs36k
    - rmbg_SEs36k
    - rmbg_SEs36k
    - rmbg_SEs36k
    data/transform/test/params/base_aug_params/mask_params/how_to_process:
    - small_patch
    - small_patch
    - small_patch
    - small_patch
    - rm_background
    - rm_background
    - rm_background
    - rm_background
