infra:
  exp_name: ts2/scbench_uni
  log_dir: /nfs/turbo/umms-tocho-snr/exp/chengjia 
  comment: smpt_SEBENCH_smcr
  log_gpu: True
  seed: 1000
  float32_matmul_precision: medium

data:
  set: scsrh_bench
  transform:
    test:
      which: HistologyTransform
      params:
        base_aug_params:
          laser_noise_config: null
          get_third_channel_params:
            mode: three_channels
            subtracted_base: 0.07629394531
          mask_params:
            how_to_process: small_patch # rm_background #small_patch
            # bg_fill: [9957.5889, 10057.9795]
          to_uint8: True
        strong_aug_params:
          aug_list:
          - which: center_crop_always_apply
            params:
              size: 24
          aug_prob: 1
  test_dataset:
    which: CellBenchDataset
    params:
      data_root: /nfs/turbo/umms-tocho/code/chengjia/torchsrh2/ts2/playgrounds/scbench/
      slides_file: ./mosaic.csv
      balance_instance_class: False
    classes_reorder: [0, 1, 2, 3,4,5,6,7,8,9]
    camera_ready_classes: ['ERROR', 'glial/astrocytes', 'glial/neurons', 'glial/oligodendrocytes', 'glial/reactive_astrocytes', 'glioma/giant_cell', 'glioma/tumor_cells', 'immune/lymphocytes', 'immune/macrophages', 'proliferation/mitotic_figures']
  test_databank_dataset:
    which: CellBenchDataset
    params:
      data_root: /nfs/turbo/umms-tocho/code/chengjia/torchsrh2/ts2/playgrounds/scbench/
      slides_file: ./mosaic.csv
      balance_instance_class: False
    classes_reorder: [0, 1, 2, 3,4,5,6,7,8,9]
    camera_ready_classes: ['ERROR', 'glial/astrocytes', 'glial/neurons', 'glial/oligodendrocytes', 'glial/reactive_astrocytes', 'glioma/giant_cell', 'glioma/tumor_cells', 'immune/lymphocytes', 'immune/macrophages', 'proliferation/mitotic_figures']
  loader:
    params:
      common:
        pin_memory: False
        persistent_workers: False
        prefetch_factor: 8
        num_workers: 7
        batch_size: 256
        drop_last: False
        shuffle: False
      test: {}
      test_databank: {}
#lightning_module:
#  which: Dinov2EvalSystem
#  params:
#    model_hyperparams:
#        arch: vit_small
#        img_size: 48
#        patch_size: 4
#        #global_pool: "token"
#        #class_token: True
#        block_chunks: 4
#        ffn_bias: true
#        ffn_layer: swiglufused
#        num_register_tokens: 0
#        interpolate_antialias: false
#        interpolate_offset: 0.1
#        layerscale: 1.0e-05
#        proj_bias: true
#        qkv_bias: true
#    pretrained_weights: TODO
lightning_module:                                                          
   which: UNIEvalSystem                                                     
   params:                                                                  
       ckpt_path: /nfs/mm-isilon/brainscans/dropbox/exp/models/uni/vit_large_patch16_224.dinov2.uni_mass100k/pytorch_model.bin
testing:
  eval_mode: knn
  save_train_pred: True
  #eval_predictions: 4cf5a93d_Oct14-23-29-19_sd1000_standaloneeval_37
  knn:
    do_knn: True
    knn_params:
      batch_size: 1536
      k: 20
      t: 0.07
  tsne:
    interactive: True
    num_patches: [4096]
    which_set: [val]
    embed_images: True
    class_params:
      perplexity: 30
      learning_rate: auto
      init : pca
  nn_viz:
    query_set: val
    n_sample: 32
    target_set: val
    exclude_same_patient: True
    k: 40
#tune:
#  diagonal_items: True
#  params:
#    #data/transform/test/params/base_aug_params/mask_params/how_to_process:
#    #- small_patch
#    #- small_patch
#    #- small_patch
#    #- small_patch
#    #- small_patch
#    infra/comment:
#    - smpt_SEBENCH_smcr_epoch0-step124999
#    - smpt_SE_epoch0-step109999
#    - smpt_SE_epoch0-step119999
#    - smpt_SE_epoch0-step59999
#    - smpt_SE_epoch0-step49999
#    infra/exp_root:
#    - ts2/fmi_hdinov2_tile
#    - ts2/fmi_hdinov2_tile
#    - ts2/fmi_hdinov2_tile
#    - ts2/fmi_hdinov2_tile
#    - ts2/fmi_hdinov2_tile
#    lightning_module/params/pretrained_weights:
#    - /nfs/turbo/umms-tocho-snr/exp/chengjia/ts2/fmi_hdinov2_tile/dc0bfcd4_May02-23-35-53_sd1000_dev_tune0/models/eval/training_119999/teacher_checkpoint.pth
#    - /nfs/turbo/umms-tocho-snr/exp/chengjia/ts2/fmi_hdinov2_tile/2e7833f0_Apr30-16-49-29_sd1000_dev_tune0/models/eval/training_124999/teacher_checkpoint.pth
#    - /nfs/turbo/umms-tocho-snr/exp/chengjia/ts2/fmi_hdinov2_tile/dc0bfcd4_May02-23-35-53_sd1000_dev_tune0/models/eval/training_109999/teacher_checkpoint.pth
#    - /nfs/turbo/umms-tocho-snr/exp/chengjia/ts2/fmi_hdinov2_tile/fb392e35_May02-19-22-22_sd1000_dev_tune0/models/eval/training_119999/teacher_checkpoint.pth
#    - /nfs/turbo/umms-tocho-snr/exp/chengjia/ts2/fmi_hdinov2_tile/fc70ee5d_May05-02-18-30_sd1000_dev_tune0/models/eval/training_59999/teacher_checkpoint.pth
#    - /nfs/turbo/umms-tocho-snr/exp/chengjia/ts2/fmi_hdinov2_tile/fc70ee5d_May05-02-18-30_sd1000_dev_tune0/models/eval/training_49999/teacher_checkpoint.pth
#
