infra:
  exp_name: ts2/he_neuro_dinov2_uniinit
  log_dir: /nfs/turbo/umms-tocho-snr/exp/chengjia
  comment: dev
  log_gpu: True
  seed: 1000
  float32_matmul_precision: medium
data:
  set: he
  parser:
    which: CachedCSVParser
    params:
      cached_parser_file:
        train: /nfs/turbo/umms-tocho/code/chengjia/torchsrh2/ts2/data/tsmeta/he_neuro/05a18e32_slide_train
        trainval: /nfs/turbo/umms-tocho/code/chengjia/torchsrh2/ts2/data/tsmeta/he_neuro/05a18e32_slide_toy
  transform:
    train:
      which: HistologyTransform
      params:
        base_aug_params:
          do_normalize: False
        strong_aug_params:
          aug_list:
          - which: hidisc_dinov2_always_apply
            params: ${........dinov2_fair_config.crops}
          aug_prob: 1
    trainval: ${.train}
  dataset:
      which: SingleLevelHierarchicalDatasetMultipleViewDINOV2
      which_process_read: memmap_multi
      params:
        common:
          data_root: /nfs/mm-isilon/brainscans/dropbox/data/root_histology_db/he.plip
          num_transforms: 0
          num_samples: 2
          balance_instance_class: False
        train:
          num_instance_self_replicate: 30
        trainval: {}
ts_wrap_config:
  no_resume: True
  load_uni_ckpt:
    do: True
    ckpt_path: /nfs/mm-isilon/brainscans/dropbox/exp/models/uni/vit_large_patch16_224.dinov2.uni_mass100k/pytorch_model.bin
dinov2_fair_config:
  train:
    batch_size_per_gpu: 64
  student:
    block_chunks: 4
  optim:
    epochs: 500
    base_lr: 0.004  # learning rate for a batch size of 1024
    warmup_epochs: 10
  crops:
    global_crops_scale: [0.32, 1.0]
    local_crops_number: 4
    local_crops_scale: [0.05, 0.32]
    global_crops_size: 224
    local_crops_size: 96
tune:
  diagonal_items: true
  params:
    dinov2_fair_config/optim/base_lr:
    - 0.00005
