infra:
  exp_name: ts2/tcga_usup_dev/pjepa
  log_dir: /nfs/turbo/umms-tocho-snr/exp/chengjia
  comment: dev
  log_gpu: True
  seed: 1000
  float32_matmul_precision: medium
data:
  set: he
  parser:
    which: CachedCSVParser
    params:
      cached_parser_file:
        train: /nfs/turbo/umms-tocho/code/chengjia/torchsrh2/ts2/data/tsmeta/he_neuro/92b8ad49_slide_all
        trainval: /nfs/turbo/umms-tocho/code/chengjia/torchsrh2/ts2/data/tsmeta/he_neuro/92b8ad49_slide_toy
        test_databank: /nfs/turbo/umms-tocho/code/chengjia/torchsrh2/ts2/data/tsmeta/tcga_glioma/5f03c12d_patch_train
        test: /nfs/turbo/umms-tocho/code/chengjia/torchsrh2/ts2/data/tsmeta/tcga_glioma/5f03c12d_patch_trainval
  transform:
    train:
      which: HistologyTransform
      params:
        base_aug_params: {}
          #laser_noise_config: null
          #base_aug: three_channels
        strong_aug_params:
          aug_list:
          - which: random_horiz_flip
            params: {}
          - which: random_vert_flip
            params: {}
          - which: random_autocontrast
            params: {}
          - which: random_sharpness
            params:
              sharpness_factor: 2
          - which: color_jitter
            params:
              brightness: 0.4
              contrast: 0.4
              saturation: 0.4
              hue: 0.2
          - which: gaussian_blur
            params:
              kernel_size: 29
              sigma: 1
          - which: gaussian_noise
            params: {}
          - which: random_erasing
            params: {}
          - which: random_resized_crop
            params:
              size: 300
          aug_prob: 0.3
    trainval: ${.train}
    test:
      which: HistologyTransform
      params:
        base_aug_params: {}
        strong_aug_params:
          aug_list: []
          aug_prob: 0
  dataset:
      which: InterPatchJEPADataset
      which_process_read: memmap
      params:
        common:
          data_root: /nfs/mm-isilon/brainscans/dropbox/data/root_histology_db/he.plip
          num_transforms: 1
          num_context_samples: 1
          num_target_samples: 3
          balance_instance_class: False
        train:
          num_instance_self_replicate: 3
        trainval: {}
  test_dataset:
      which: PatchDataset
      which_process_read: memmap
      params:
          data_root: /nfs/mm-isilon/brainscans/dropbox/data/root_histology_db/he.plip
          num_transforms: 1
          balance_instance_class: False
      negative_class_index: 1
      classes_reorder: [2,0,1]
      camera_ready_classes: [Astro, GBM, Oligo]
  loader:
    params:
      common:
        pin_memory: False
        persistent_workers: True
        prefetch_factor: 2
        num_workers: 4
      train:
        batch_size: 128
        drop_last: True
        shuffle: True
      trainval:
        batch_size: 8
        drop_last: False
        shuffle: False
      test:
        batch_size: 64
        drop_last: False
        shuffle: False
    trainval_sampler:
      num_samples: 8
      replacement: False
lightning_module:
  which: InterPatchJEPASystem
  params:
    model_hyperparams:
      backbone_cf:
        which: resnet34
        params: {}
        #  img_size: 224
        #  patch_size: 16
        #  global_pool: ""
        #  class_token: False
      pred_params:
        predictor_embed_dim: 512
        depth: 6
        drop_path_rate: 0.0
        init_std: 0.02
        pos_emb_params:
          prefix_len: 0
          pos_emb_grad: True
        block_params:
          num_heads: 4
          mlp_ratio: 4.0
          qkv_bias: True
          qk_scale: null
          drop: 0.0
          attn_drop: 0.0
    loss_params: {}
    ema_beta: 0.99
    opt_cf:
      which: adamw
      scale_lr: True
      params:
        lr: 0.001
        betas: [0.9, 0.999]
        eps: 1.0e-8
        weight_decay: 0.01
        amsgrad: False
    #opt_cf:
    #  which: lars
    #  scale_lr: True
    #  params:
    #    lr: 0.001
    #    weight_decay: 1.0e-4
    #    momentum: 0.9
    #    #eta: 0.001
    schd_cf:
      which: cos_linear_warmup
      params:
        num_warmup_steps: 0.1
        num_cycles: 0.5
training:
  resume_checkpoint: null
  trainer_params:
    max_epochs: 40
    gradient_clip_val: 0.5
    enable_progress_bar: True
    precision: 'bf16-mixed'
    deterministic: False
  trainval:
    freq:
      interval: 2
      unit: "epoch"
testing:
  #lightning_module:
  #  which: InterPatchJEPASystem
  #  params:
  #    model_hyperparams:
  #      backbone_cf:
  #        which: vit_tiny
  #        params:
  #          img_size: 224
  #          patch_size: 16
  #          global_pool: "avg"
  #          fc_norm: False
  #          class_token: False
  #      pred_params:
  #        predictor_embed_dim: 192
  #        depth: 6
  #        drop_path_rate: 0.0
  #        init_std: 0.02
  #        pos_emb_params:
  #          prefix_len: 0
  #          pos_emb_grad: True
  #        block_params:
  #          num_heads: 4
  #          mlp_ratio: 4.0
  #          qkv_bias: True
  #          qk_scale: null
  #          drop: 0.0
  #          attn_drop: 0.0
  eval_mode: patch_knn
  save_train_pred: true
  knn:
    do_knn: True
    knn_params:
      batch_size: 1536
      k: 20
      t: 0.07
  tsne:
    interactive: False
    num_patches: [8192]
    which_set: [val]
    embed_images: true
    class_params:
      perplexity: 50
      learning_rate: auto
      init : pca
tune:
  diagonal_items: true
  params:
    lightning_module/params/opt_cf/params/lr:
    - 0.0001
    - 0.001
    - 0.01
    - 0.00001
    infra/comment:
    - pjepa_1000_lr0.0001
    - pjepa_1000_lr0.001
    - pjepa_1000_lr0.01
    - pjepa_1000_lr0.00001
