infra:
  exp_name: ts2/he_neuro_vit2/simclr_vitb
  log_dir: /nfs/turbo/umms-tocho-snr/exp/chengjia
  comment: dev
  log_gpu: True
  seed: 1000
  float32_matmul_precision: medium
data:
  set: he
  parser:
    which: CachedCSVParser
    params:
      cached_parser_file:
        train: /nfs/turbo/umms-tocho/code/chengjia/torchsrh2/ts2/data/tsmeta/he_neuro/aa666ea1_slide_all
        trainval: /nfs/turbo/umms-tocho/code/chengjia/torchsrh2/ts2/data/tsmeta/he_neuro/aa666ea1_slide_toy
        test_databank: /nfs/turbo/umms-tocho/code/chengjia/torchsrh2/ts2/data/tsmeta/tcga_glioma/3438b0a3_patch40_train
        test: /nfs/turbo/umms-tocho/code/chengjia/torchsrh2/ts2/data/tsmeta/tcga_glioma/3438b0a3_patch40_trainval
  transform:
    train:
      which: HistologyTransform
      params:
        base_aug_params: {}
          #laser_noise_config: null
          #base_aug: three_channels
        strong_aug_params:
          aug_list:
          - which: resize_always_apply
            params:
              size: 224
          - which: random_horiz_flip
            params: {}
          - which: random_vert_flip
            params: {}
          - which: color_jitter
            params:
              brightness: 0.4
              contrast: 0.4
              saturation: 0.4
              hue: 0.2
          - which: gaussian_blur
            params:
              kernel_size: 29
              sigma: 1
          - which: gaussian_noise
            params: {}
          - which: random_resized_crop
            params:
              size: 224
          aug_prob: 0.3
    trainval: ${.train}
    test:
      which: HistologyTransform
      params:
        base_aug_params: {}
        strong_aug_params:
          aug_list:
          - which: resize_always_apply
            params:
              size: 224
          aug_prob: 1
  dataset:
      which: SingleLevelHierarchicalDataset
      which_process_read: memmap_multi
      params:
        common:
          data_root: /nfs/mm-isilon/brainscans/dropbox/data/root_histology_db/he.plip
          num_transforms: 2
          num_samples: 1
          balance_instance_class: False
        train:
          num_instance_self_replicate: 30
        trainval: {}
  test_dataset:
      which: PatchDataset
      which_process_read: memmap
      params:
          data_root: /nfs/mm-isilon/brainscans/dropbox/data/root_histology_db/he.plip
          num_transforms: 1
          balance_instance_class: False
      negative_class_index: 1
      classes_reorder: [2,0,1]
      camera_ready_classes: [Astro, GBM, Oligo]
  loader:
    params:
      common:
        pin_memory: False
        persistent_workers: True
        prefetch_factor: 12
        num_workers: 7
      train:
        batch_size: 256
        drop_last: True
        shuffle: True
      trainval:
        batch_size: 8
        drop_last: False
        shuffle: False
      test:
        batch_size: 64
        drop_last: False
        shuffle: False
    trainval_sampler:
      num_samples: 8
      replacement: False
dinov2_fair_config:
  train:
    dataset_path: ImageNet:split=TRAIN
    batch_size_per_gpu: 64
  student:
    block_chunks: 4
tune:
  diagonal_items: true
  params:
    infra/comment:
    - simclr_1000_lr0.001
    - simclr_1000_lr0.0001
