infra:
  exp_name: ts2/umbtb/vitl_uniinit
  log_dir: /nfs/turbo/umms-tocho-snr/exp/chengjia
  comment: dev
  log_gpu: True
  seed: 1000
  float32_matmul_precision: medium
data:
  set: he
  parser:
    which: CachedCSVParser
    params:
      cached_parser_file:
        train: /nfs/turbo/umms-tocho/code/chengjia/torchsrh2/ts2/data/tsmeta/umbtb_bench/d6503809_slide_train
        trainval: /nfs/turbo/umms-tocho/code/chengjia/torchsrh2/ts2/data/tsmeta/umbtb_bench/d6503809_slide_valtest
        test_databank: /nfs/turbo/umms-tocho/code/chengjia/torchsrh2/ts2/data/tsmeta/umbtb_bench/c808f0f1_patch40_train
        test: /nfs/turbo/umms-tocho/code/chengjia/torchsrh2/ts2/data/tsmeta/umbtb_bench/c808f0f1_patch40_valtest
  transform:
    train:
      which: HistologyTransform
      params:
        base_aug_params: {}
          #laser_noise_config: null
          #base_aug: three_channels
        strong_aug_params:
          aug_list:
          - which: resize_always_apply
            params:
              size: 224
          - which: random_horiz_flip
            params: {}
          - which: random_vert_flip
            params: {}
          - which: color_jitter
            params:
              brightness: 0.4
              contrast: 0.4
              saturation: 0.4
              hue: 0.2
          - which: gaussian_blur
            params:
              kernel_size: 29
              sigma: 1
          - which: gaussian_noise
            params: {}
          - which: random_resized_crop
            params:
              size: 224
          aug_prob: 0.3
    trainval: ${.train}
    test:
      which: HistologyTransform
      params:
        base_aug_params: {}
        strong_aug_params:
          aug_list:
          - which: resize_always_apply
            params:
              size: 224
          aug_prob: 1
  dataset:
      which: SingleLevelHierarchicalDataset
      which_process_read: memmap_multi
      params:
        common:
          data_root: /nfs/mm-isilon/brainscans/dropbox/data/root_histology_db/he.plip
          num_transforms: 2
          num_samples: 1
          balance_instance_class: True
        train:
          num_instance_self_replicate: 30
        trainval: {}
  test_dataset:
      which: PatchDataset
      which_process_read: memmap
      params:
          data_root: /nfs/mm-isilon/brainscans/dropbox/data/root_histology_db/he.plip
          num_transforms: 1
          balance_instance_class: False
      negative_class_index: 1
      classes_reorder: [0,  1,  2,  3,  4,  5,  6]
      camera_ready_classes: [diffuse_hgg, diffuse_lgg, mening, circum_glioma, mets, embryonal, pseudo]
  loader:
    params:
      common:
        pin_memory: False
        persistent_workers: True
        prefetch_factor: 12
        num_workers: 7
      train:
        batch_size: 64
        drop_last: True
        shuffle: True
      trainval:
        batch_size: 8
        drop_last: False
        shuffle: False
      test:
        batch_size: 64
        drop_last: False
        shuffle: False
    trainval_sampler:
      num_samples: 8
      replacement: False
lightning_module:
  which: SupConSystem
  params:
    model_hyperparams:
      backbone_cf:
        which: vit_large #resnet34
        params:
          img_size: 224
          patch_size: 16
          global_pool: "token"
          class_token: True
          init_values: 1.0e-6
      proj_params:
        hidden_layers: [1024,1024]
        n_out: 1024
        activation: relu
        drop: 0
        bias: True
    loss_params: {}
    opt_cf:
      which: adamw
      scale_lr: True
      params:
        lr: 0.001
        betas: [0.9, 0.999]
        eps: 1.0e-8
        weight_decay: 0.01
        amsgrad: False
    #opt_cf:
    #  which: lars
    #  scale_lr: True
    #  params:
    #    lr: 0.001
    #    weight_decay: 1.0e-4
    #    momentum: 0.9
    #    #eta: 0.001
    schd_cf:
      which: cos_linear_warmup
      params:
        num_warmup_steps: 0.1
        num_cycles: 0.5
training:
  resume_checkpoint: null
  load_backbone:
    ckpt_path: /nfs/mm-isilon/brainscans/dropbox/exp/models/uni/vit_large_patch16_224.dinov2.uni_mass100k/pytorch_model.bin
    remove_prefix: null
  trainer_params:
    max_epochs: 100
    gradient_clip_val: 0.5
    enable_progress_bar: True
    precision: 'bf16-mixed'
    deterministic: False
  trainval:
    freq:
      interval: 10
      unit: "epoch"
testing:
  eval_mode: patch_knn
  save_train_pred: true
  knn:
    do_knn: True
    knn_params:
      batch_size: 1536
      k: 200
      t: 0.07
  tsne:
    interactive: False
    num_patches: [8192]
    which_set: [val]
    embed_images: true
    class_params:
      perplexity: 50
      learning_rate: auto
      init : pca
tune:
  diagonal_items: true
  params:
    lightning_module/params/opt_cf/params/lr:
    - 0.000005
    - 0.0000005
    - 0.0000001
    infra/comment:
    - supcon_1000_lr0.000005 
    - supcon_1000_lr0.0000005
    - supcon_1000_lr0.0000001
